config/routes.rb
Rails.application.routes.draw do

  # profiles
  resources :profiles, :controller => 'muck/profiles' do
    collection do
      get :search
    end
  end
  
  resources :users do
    resource :profile, :controller => 'muck/profiles'
  end
  
  namespace :admin do
    resources :profiles, :controller => 'muck/profiles'
  end
    
end

app/controllers/admin/muck/profiles_controller.rb
class Admin::Muck::ProfilesController < Admin::Muck::BaseController
  
  def edit
    respond_to do |format|
      format.html { render :template => 'admin/profiles/edit' }
    end
  end

end

app/controllers/muck/profiles_controller.rb
class Muck::ProfilesController < ApplicationController
  
  before_filter :setup_user, :only => [:show, :edit]
  
  def index
    @per_page = 400
    @users = User.by_newest.paginate(:page => @page, :per_page => @per_page, :include => 'profile')
    respond_to do |format|
      format.html { render :template => 'profiles/index' }
    end
  end

  def search
    @query = params[:q]
    @page = (params[:page] || 1).to_i
    @rows = (params[:rows] || 10).to_i
    if MuckProfile.configuration.enable_solr
      results = Profile.find_by_solr(@query, :limit => @rows, :offset => @rows*(@page-1), :core => 'en')
      @hit_count = results.total
      @users = results.results.paginate(:page => @page, :per_page => @rows, :total_entries => @hit_count)
    elsif MuckProfile.configuration.enable_sunspot
      results = Sunspot.search Profile do
        keywords @query
        paginate :page => @page, :per_page => @per_page
      end      
      @hit_count = results.total
      @users = results.results.paginate(:page => @page, :per_page => @rows, :total_entries => @hit_count)
    else
      raise translate('muck.profiles.search_not_enabled')
    end
    
    respond_to do |format|
      format.html { render :template => 'profiles/index' }
    end
  end

  # show a given user's public profile information
  def show
    @profile = @user.profile
    @page_title = @user.display_name
    respond_to do |format|
      format.html { render :template => 'profiles/show' }
    end
  end

  # Renders an edit for for the current user's profile
  #
  # It is simple to override the edit template.  Simply create a template in app/views/profiles/edit.html.erb 
  # and add something similar to the following:
  #    <div id="edit_profile">
  #      <%= output_errors(t('muck.profiles.problem_editing_profile'), {:class => 'help-box'}, @profile) %>
  #      <%= profile_form(@user) do |f| -%>
  #        <%# Add custom fields here.  ie %>
  #        <%= f.text_field :custom_thing %>
  #      <% end -%>
  #    </div>
  def edit
    @profile = @user.profile
    @page_title = t('muck.profiles.edit_profile_title', :name => @user.display_name)
    respond_to do |format|
      format.pjs { render :template => 'profiles/edit', :layout => false } # fancybox request 
      format.html { render :template => 'profiles/edit' }
    end
  end
  
  def update
    @user = User.find(params[:user_id])
    @profile = @user.profile
    @page_title = t('muck.profiles.edit_profile_title', :name => @user.display_name)
    @user.update_attributes!(params[:user])
    respond_to do |format|
      flash[:notice] = t('muck.profiles.edit_success')
      format.html { redirect_back_or_default edit_user_profile_path(@user) }
    end
  rescue ActiveRecord::RecordInvalid => ex
    flash[:error] = t('muck.profiles.edit_failure')
    render :action => :edit
  end

  protected
    def setup_user
      if params[:user_id]
        @user = User.find(params[:user_id]) rescue nil
      end
      @user ||= User.find(params[:id])
    end
end

app/helpers/muck_profiles_helper.rb
module MuckProfilesHelper

  # Renders a profile edit form
  # content:  Optional content object to be edited.
  # options:  html options for form.  For example:
  #             :html => {:id => 'a form'}
  def profile_form(user, options = {}, &block)
    options[:html] = {} if options[:html].nil?
    raw_block_to_partial('profiles/form', options.merge(:user => user), &block)
  end
  
  # Outputs a link and text that guesses the user's location using their ip.
  def location_suggestion(field_id)
    geo = Geokit::Geocoders::MultiGeocoder.geocode(request.ip)
    location = readable_location(geo)
    return '' if location.blank?
    render :partial => 'profiles/location_suggestion', :locals => { :field_id => field_id, :location => location }
  end
  
  # Turns a geokit location object into a location string with city, state country
  def readable_location(location)
    return '' if location.city.blank? && location.state.blank? && location.province.blank? && location.country_code.blank?
    "#{location.city}, #{location.state || location.province} #{location.country_code}"
  end
  
end

app/views/profiles/_form.erb
<div id="<%= "#{user.dom_id}" %>" class="edit_profile">
  <%= muck_form_for(user, :url => user_profile_path(user), :html => html.merge(:id => "edit-profile-form", :name => 'edit-profile-form', :method => :put, :multipart => true ) ) do |f| -%>
    <%= capture(f, &block) if block -%>
    <div id="edit_profile_submit" class="button form-row">
      <%= f.submit t('muck.general.update') %>
    </div>
  <% end %>
</div>

app/views/profiles/_location_suggestion.erb
<div class="location-suggestion">
  <%= I18n.t('muck.profiles.location_suggestion', :location => location) %>
  <a href="#" id="set_<%=field_id%>"><%=I18n.t('muck.profiles.click_to_set')%></a>
</div>
<% content_for :javascript do -%>
<script type="text/javascript">
jQuery(document).ready(function() {
	jQuery("#set_<%=field_id%>").click(function() {
		jQuery("#<%=field_id%>").val("<%=location%>");
		return false;
	});
});
</script>
<% end -%>

app/views/profiles/_location_suggestion.html.erb
<div class="location-suggestion">
  <%= I18n.t('muck.profiles.location_suggestion', :location => location) %>
  <a href="#" id="set_<%=field_id%>"><%=I18n.t('muck.profiles.click_to_set')%></a>
</div>
<script type="text/javascript">
jQuery(document).ready(function() {
	jQuery("#set_<%=field_id%>").click(function() {
		jQuery("#<%=field_id%>").val("<%=location%>");
		return false;
	});
});
</script>

app/views/profiles/_profile.erb
<div class="user-profile-small">
  <%= icon user, :tiny %>
  <%= link_to user.display_name, profile_path(user) %>
</div>

app/views/profiles/_profile.html.erb
<div class="user-profile-small">
  <%= icon user, :tiny %>
  <%= link_to user.display_name, profile_path(user) %>
</div>

app/views/profiles/_profile_icon.erb
<div class="user-profile-icon">
  <%= icon user, :icon %>
  <%= link_to user.display_name, profile_path(user) %>
</div

app/views/profiles/_profile_icon.html.erb
<div class="user-profile-icon">
  <%= icon user, :icon %>
  <%= link_to user.display_name, profile_path(user) %>
</div

app/views/profiles/edit.erb
<% mce_id = "#{@profile.dom_id}_content"
location_id = 'location' -%>
<%= tiny_mce_messages_and_scripts_for(mce_id, @profile) %>
<%= country_scripts %>
<div id="edit_content" class="span-24 colborder column">
  <%= output_errors(t('muck.profiles.problem_editing_profile'), {:class => 'help-box'}, @profile) %>
  <%= profile_form(@user) do |f| -%>
    <%# can add form fields as desired here -%>
    <%= f.text_field :first_name, { :label => t('muck.users.first_name') } %>
    <%= f.text_field :last_name, { :label => t('muck.users.last_name') } %>
    <%= f.text_field :email, { :label => t('muck.users.email') } %>
    <%= f.fields_for(:profile, :builder => MuckEngine::FormBuilder) do |pf| %>
      <div id="edit_profile_image">
        <%= icon @user, :thumb %>
        <%= pf.file_field :photo, { :label => t('muck.profiles.upload_photo') } %>
      </div>
      <%= pf.text_field :location, {:id => location_id, :class => 'tags', :tip => t('muck.profiles.location_help'), :label => t('muck.profiles.location') } %>
      <%= location_suggestion(location_id) if @profile.location.blank? && MuckProfiles.configuration.enable_geokit %>
      <%#= pf.text_field :skill_list, {:class => 'tags', :tip => t('muck.profiles.skills_help'), :label => t('muck.profiles.skills') } %>
      <%#= pf.text_field :interest_list, {:class => 'tags', :tip => t('muck.profiles.interests_help'), :label => t('muck.profiles.interests') } %>
      <%= pf.state_select(:state_id, {:tip => t('muck.profiles.state_help'), :label => t('muck.profiles.state')}) %>
      <%= pf.country_select(:country_id, {:tip => t('muck.profiles.country_help'), :label => t('muck.profiles.country')}) %>
      <%= pf.language_select(:language_id, {:tip => t('muck.profiles.language_help'), :label => t('muck.profiles.language')}) %>
      <%= pf.text_area :about, { :label => t('muck.profiles.about'),
                                :class => 'mceEditor',
                                :id => mce_id} %>
    <% end %>
  <% end -%>
</div>

app/views/profiles/index.html.erb
<%= form_tag search_profiles_path, :method => 'GET' do -%>
    <%= text_field_tag :q, @query || '' %>
    <input type="submit" value="Search" />
<% end -%>

<% if !@query.blank? %>
<div><%= link_to 'Clear query', profiles_path %></div>
<% end %>

<div id="profiles">
  <%= render :partial => 'profiles/profile_icon', :collection => @users, :as => :user %>
</div>

app/views/profiles/show.html.erb
<div class="span-24 colborder column">
  <%= icon @user, :thumb %>
  <p><%= @user.full_name %></p>
  <p><%= link_to t('muck.profiles.edit_profile'), edit_user_profile_path(@user) if @profile.can_edit?(current_user) %></p>
</div>